class ConfigPersonagem:
    SCREEN_HEIGHT = 600
    SCREEN_WIDTH = 1000
    FPS = 60
    LARGURA_PERSONAGEM = 0.1 * SCREEN_WIDTH
    ALTURA_PERSONAGEM = 0.1 * SCREEN_HEIGHT
    POSX_PERSONAGEM = SCREEN_WIDTH / 2 - LARGURA_PERSONAGEM /2
    POSY_PERSONAGEM = SCREEN_HEIGHT / 2 - ALTURA_PERSONAGEM /2
    COR_PERSONAGEM = 'blue'
    VEL_PERSONAGEM = 10
    
    
