class ConfigPersonagem:
    SCREEN_HEIGHT = 600
    SCREEN_WIDTH = 1000
    FPS = 60
    RAIO_PERSONAGEM =  (0.03 * SCREEN_WIDTH) + (0.03 * SCREEN_HEIGHT)
    DIAMETRO_PERSONAGEM =  2 * ((0.03 * SCREEN_WIDTH) + (0.03 * SCREEN_HEIGHT))
    LARGURA_PERSONAGEM = 0.1 * SCREEN_WIDTH
    ALTURA_PERSONAGEM = 0.1 * SCREEN_HEIGHT
    POSX_PERSONAGEM = SCREEN_WIDTH / 2 
    POSY_PERSONAGEM = SCREEN_HEIGHT / 2 
    COR_PERSONAGEM = 'blue'
    VEL_PERSONAGEM = 10
    
    
